# Generated by Django 3.2.5 on 2021-07-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speech_text', models.TextField(unique=True)),
                ('sentiment', models.CharField(max_length=10, null=True)),
                ('sentiment_acc', models.FloatField(null=True)),
                ('topic', models.CharField(max_length=20, null=True)),
                ('topic_acc', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('sentiment', models.CharField(max_length=10, null=True)),
                ('sentiment_acc', models.FloatField(null=True)),
                ('topic', models.CharField(max_length=20, null=True)),
                ('topic_acc', models.FloatField(null=True)),
            ],
        ),
    ]
