# Generated by Django 3.2.5 on 2021-08-06 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210728_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataprediction',
            name='data',
        ),
    ]
