# Generated by Django 3.2.5 on 2021-11-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_dataprediction_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprediction',
            name='sentiment_acc',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='sentiment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='topic',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
