# Generated by Django 3.2.5 on 2021-11-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20211122_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprediction',
            name='topic_acc',
            field=models.FloatField(null=True),
        ),
    ]
